In [5]:
import torch
import numpy as np

In [6]:
arr=[[1,2],[3,4]]

In [7]:
np.array(arr)

array([[1, 2],
       [3, 4]])

# import したい

# pytorchでテンソルを作る

In [8]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

# numpyを利用して11行列を作る

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# Pytorchを利用して同じことをする

In [11]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

# random変数を入れた行列を作る

In [13]:
np.random.rand(2,2)

array([[0.74474564, 0.84294983],
       [0.6022692 , 0.89280907]])

# pytorchを利用して同じことをする

In [14]:
torch.rand(2,2)

tensor([[0.8385, 0.9089],
        [0.5173, 0.1108]])

# Random seed→再現性の話

In [16]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

## Seedの再現性の話
seedの指定をしない場合、ランダムな数値が出る

In [19]:
np.random.rand(2,2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

## 再度seedを指定してみると？

In [20]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

# pytorchでもnumpyと同じようになるよ

In [21]:
torch.rand(2,2)

tensor([[0.7665, 0.2776],
        [0.0717, 0.5329]])

In [24]:
torch.manual_seed(0)
print(torch.rand(2,2))
torch.manual_seed(0)
print(torch.rand(2,2))

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


# GPUを利用するときのランダムシードは異なる
iMacではできないらしい

In [29]:
print(torch.cuda.is_available())

False


# NumpyとTorchの橋渡し

In [30]:
np_array=np.ones((2,2))

In [31]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [32]:
print(type(np_array))

<class 'numpy.ndarray'>


# torch tensorへの変換(numpy.array)

In [33]:
torch_tensor = torch.from_numpy(np_array)

In [34]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [36]:
print(type(torch_tensor))

<class 'torch.Tensor'>


# Tensorの型を指定して渡したいとき

## numpyの整数型の行列を作る

In [37]:
np_array_new = np.ones((2,2), dtype=np.int8)

### 講義では変換できないと言われていたができるようになっているｗ

In [40]:
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

# TorchからNumpyへ移行

In [41]:
torch_tensor = torch.ones(2,2)

In [43]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [44]:
torch_to_numpy = torch_tensor.numpy()

In [45]:
torch_to_numpy

array([[1., 1.],
       [1., 1.]], dtype=float32)

# GPU <-> CPU
のちにこの使い分けが非常に重要になる

In [46]:
# CPU
tensor_cpu = torch.ones(2,2)

In [47]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [48]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])